### ISSUE TITLE
Edit Navbar

### ISSUE THREAD

**Issue by Om-Thorat** [Ctrl-Crew/sih#9]
Edit Navbar to include 
* Post audit report
* Audit config
* Home
* Trigger Audit
* Targets

And a shiny button for Trigger Audit.

**Comment by Om-Thorat** [comment]
@Zapper9982 Please do `me`

**Comment by Zapper9982** [comment]
:) bhai i didnt push it yet

**Comment by Om-Thorat** [comment]
exactly what is premature ...... ?

**Comment by Zapper9982** [comment]
please provide icon suggestions

**Comment by ritankarsaha** [comment]
@Zapper9982 Bhai i don't remember closing this🥲. @rohansen856 did u? he was sitting with my laptop this whole time lol

**Comment by Zapper9982** [comment]
no problem it is understandable anyways i have laid out routes and page.tsx in each route , however the Home page should be rendered in the page.tsx of /app/ folder please perform the same .
